import 'package:http/http.dart' as http;
import 'dart:convert';
import './Country.dart';

class Countries {
  final Map<String, List> _codeToArea = {
    "ABW": ["Aruba", "AW"],
    "AFG": ["Afghanistan", "AF"],
    "AGO": ["Angola", "AO"],
    "ALB": ["Albania", "AL"],
    "AND": ["Andorra", "AD"],
    "ARE": ["United Arab Emirates", "AE"],
    "ARG": ["Argentina", "AR"],
    "ARM": ["Armenia", "AM"],
    "ASM": ["American Samoa", "AS"],
    "ATG": ["Antigua and Barbuda", "AG"],
    "AUS": ["Australia", "AU"],
    "AUT": ["Austria", "AT"],
    "AZE": ["Azerbaijan", "AZ"],
    "BDI": ["Burundi", "BI"],
    "BEL": ["Belgium", "BE"],
    "BEN": ["Benin", "BJ"],
    "BFA": ["Burkina Faso", "BF"],
    "BGD": ["Bangladesh", "BD"],
    "BGR": ["Bulgaria", "BG"],
    "BHR": ["Bahrain", "BH"],
    "BHS": ["Bahamas", "BS"],
    "BIH": ["Bosnia and Herzegovina", "BA"],
    "BLR": ["Belarus", "BY"],
    "BLZ": ["Belize", "BZ"],
    "BMU": ["Bermuda", "BM"],
    "BOL": ["Bolivia", "BO"],
    "BRA": ["Brazil", "BR"],
    "BRB": ["Barbados", "BB"],
    "BRN": ["Brunei", "BN"],
    "BTN": ["Bhutan", "BT"],
    "BWA": ["Bhutan", "BW"],
    "CAF": ["Central African Republic", "CF"],
    "CAN": ["Canada", "CA"],
    "CHE": ["Switzerland", "CH"],
    "CHI": ["Cocos (Keeling) Islands", "CC"],
    "CHL": ["Chile", "CL"],
    "CHN": ["China", "CN"],
    "CIV": ["Ivory Coast", "CI"],
    "CMR": ["Cameroon", "CM"],
    "COD": ["Democratic Republic of the Congo", "CD"],
    "COG": ["Republic of the Congo", "CG"],
    "COL": ["Colombia", "CO"],
    "COM": ["Comoros", "KM"],
    "CPV": ["Cape Verde", "CV"],
    "CRI": ["Costa Rica", "CR"],
    "CUB": ["Cuba", "CU"],
    "CUW": ["Curacao", "CW"],
    "CYM": ["Cayman Islands", "KY"],
    "CYP": ["Cyprus", "CY"],
    "CZE": ["Czech Republic", "CZ"],
    "DEU": ["Germany", "DE"],
    "DJI": ["Djibouti", "DJ"],
    "DMA": ["Dominica", "DM"],
    "DNK": ["Denmark", "DK"],
    "DOM": ["Dominican Republic", "DO"],
    "DZA": ["Algeria", "DZ"],
    "ECU": ["Ecuador", "EC"],
    "EGY": ["Egypt", "EG"],
    "ERI": ["Eritrea", "ER"],
    "ESP": ["Spain", "ES"],
    "EST": ["Estonia", "EE"],
    "ETH": ["Ethiopia", "ET"],
    "FIN": ["Finland", "FI"],
    "FJI": ["Fiji", "FJ"],
    "FRA": ["France", "FR"],
    "FRO": ["Faroe Islands", "FO"],
    "FSM": ["Micronesia", "FM"],
    "GAB": ["Gabon", "GA"],
    "GBR": ["United Kingdom", "GB"],
    "GEO": ["Georgia", "GE"],
    "GHA": ["Ghana", "GH"],
    "GIB": ["Gibraltar", "GI"],
    "GIN": ["Guinea", "GN"],
    "GMB": ["Gambia", "GM"],
    "GNB": ["Guinea-Bissau", "GW"],
    "GNQ": ["Equatorial Guinea", "GQ"],
    "GRC": ["Greece", "GR"],
    "GRD": ["Grenada", "GD"],
    "GRL": ["Greenland", "GL"],
    "GTM": ["Guatemala", "GT"],
    "GUM": ["Guam", "GU"],
    "GUY": ["Guyana", "GY"],
    "HKG": ["Hong Kong", "HK"],
    "HND": ["Honduras", "HN"],
    "HRV": ["Croatia", "HR"],
    "HTI": ["Haiti", "HT"],
    "HUN": ["Hungary", "HU"],
    "IDN": ["Indonesia", "ID"],
    "IMN": ["Isle of Man", "IM"],
    "IND": ["India", "IN"],
    "IRL": ["Ireland", "IE"],
    "IRN": ["Iran", "IR"],
    "IRQ": ["Iraq", "IQ"],
    "ISL": ["Iceland", "IS"],
    "ISR": ["Israel", "IL"],
    "ITA": ["Italy", "IT"],
    "JAM": ["Jamaica", "JM"],
    "JOR": ["Jordan", "JO"],
    "JPN": ["Japan", "JP"],
    "KAZ": ["Kazakhstan", "KZ"],
    "KEN": ["Kenya", "KE"],
    "KGZ": ["Kyrgyzstan", "KG"],
    "KHM": ["Cambodia", "KH"],
    "KIR": ["Kiribati", "KI"],
    "KNA": ["Saint Kitts and Nevis", "KN"],
    "KOR": ["South Korea", "KR"],
    "KWT": ["Kuwait", "KW"],
    "LAO": ["Laos", "LA"],
    "LBN": ["Lebanon", "LB"],
    "LBR": ["Liberia", "LR"],
    "LBY": ["Lybia", "LB"],
    "LCA": ["Saint Lucia", "LC"],
    "LIE": ["Liechtenstein", "LI"],
    "LKA": ["Sri Lanka", "LK"],
    "LSO": ["Lesotho", "LS"],
    "LTU": ["Lithuania", "LT"],
    "LUX": ["Luxembourg", "LU"],
    "LVA": ["Latvia", "LV"],
    "MAC": ["Macao", "MO"],
    "MAF": ["Saint Martin", "MF"],
    "MAR": ["Morocco", "MA"],
    "MCO": ["Monaco", "MC"],
    "MDA": ["Moldova", "MD"],
    "MDG": ["Madagascar", "MG"],
    "MDV": ["Maldives", "MV"],
    "MEX": ["Mexico", "MX"],
    "MHL": ["Marshall Islands", "MH"],
    "MKD": ["Macedonia", "MK"],
    "MLI": ["Mali", "ML"],
    "MLT": ["Malta", "MT"],
    "MMR": ["Myanmar", "MM"],
    "MNE": ["Montenegro", "ME"],
    "MNG": ["Mongolia", "MN"],
    "MNP": ["Northern Mariana Islands", "MP"],
    "MOZ": ["Mozambique", "MZ"],
    "MRT": ["Mauritania", "MR"],
    "MUS": ["Mauritius", "MU"],
    "MWI": ["Malawi", "MW"],
    "MYS": ["Malaysia", "MY"],
    "NAM": ["Namibia", "NA"],
    "NCL": ["New Caledonia", "NC"],
    "NER": ["Niger", "NE"],
    "NGA": ["Nigeria", "NG"],
    "NIC": ["Nicaragua", "NI"],
    "NLD": ["Netherlands", "NL"],
    "NOR": ["Norway", "NO"],
    "NPL": ["Nepal", "NP"],
    "NRU": ["Nauru", "NR"],
    "NZL": ["New Zealand", "NZ"],
    "OMN": ["Oman", "OM"],
    "PAK": ["Pakistan", "PK"],
    "PAN": ["Panama", "PA"],
    "PER": ["Peru", "PE"],
    "PHL": ["Philippines", "PH"],
    "PLW": ["Palau", "PW"],
    "PNG": ["Papua New Guinea", "PG"],
    "POL": ["Poland", "PL"],
    "PRI": ["Puerto Rico", "PR"],
    "PRK": ["North Korea", "KP"],
    "PRT": ["Portugal", "PT"],
    "PRY": ["Paraguay", "PY"],
    "PSE": ["Palestinian Territoy", "PS"],
    "PYF": ["French Polynesia", "PF"],
    "QAT": ["Qatar", "QA"],
    "ROU": ["Romania", "RO"],
    "RUS": ["Russia", "RU"],
    "RWA": ["Rwanda", "RW"],
    "SAU": ["Saudi Arabia", "SA"],
    "SDN": ["Sudan", "SD"],
    "SEN": ["Senegal", "SN"],
    "SGP": ["Singapore", "SG"],
    "SLB": ["Solomon Islands", "SB"],
    "SLE": ["Sierra Leone", "SL"],
    "SLV": ["El Salvador", "SV"],
    "SMR": ["San Marino", "SM"],
    "SOM": ["Somalia", "SO"],
    "SRB": ["Serbia", "RS"],
    "SSD": ["South Sudan", "SS"],
    "STP": ["Sao Tome and Principe", "ST"],
    "SUR": ["Suriname", "SR"],
    "SVK": ["Slovakia", "SK"],
    "SVN": ["Slovenia", "SI"],
    "SWE": ["Sweden", "SE"],
    "SWZ": ["Swaziland", "SZ"],
    "SXM": ["Sint Maarten", "SX"],
    "SYC": ["Seychelles", "SC"],
    "SYR": ["Syria", "SY"],
    "TCA": ["Turks and Caicos Islands", "TC"],
    "TCD": ["Chad", "TD"],
    "TGO": ["Togo", "TG"],
    "THA": ["Thailand", "TH"],
    "TJK": ["Tajikistan", "TJ"],
    "TKM": ["Turkmenistan", "TM"],
    "TLS": ["East Timor", "TL"],
    "TON": ["Tonga", "TO"],
    "TTO": ["Trinidad and Tobago", "TT"],
    "TUN": ["Tunisia", "TN"],
    "TUR": ["Turkey", "TR"],
    "TUV": ["Tuvalu", "TV"],
    "TWN": ["Taiwan", "TW"],
    "TZA": ["Tanzania", "TZ"],
    "UGA": ["Uganda", "UG"],
    "UKR": ["Ukraine", "UA"],
    "URY": ["Uruguay", "UY"],
    "USA": ["United States", "US"],
    "UZB": ["Uzbekistan", "UZ"],
    "VCT": ["Saint Vincent and the Grenadines", "VC"],
    "VEN": ["Venezuela", "VE"],
    "VGB": ["British Virgin Islands", "VG"],
    "VIR": ["U.S. Virgin Islands", "VI"],
    "VNM": ["Vietnam", "VN"],
    "VUT": ["Vanuatu", "VU"],
    "WSM": ["Samoa", "WS"],
    "XKX": ["Kosovo", "XK"],
    "YEM": ["Yemen", "YE"],
    "ZAF": ["South Africa", "ZA"],
    "ZMB": ["Zambia", "ZM"],
    "ZWE": ["Zimbabwe", "ZW"]
  };

  Countries();

  fetchData() async {
    String url =
        "http://api.worldbank.org/v2/sources/2/country/all/metatypes/incomegroup/metadata?format=json";
    var data = await http.get(url);
    var jsonData = json.decode(data.body);
    var dataCountries = jsonData["source"][0]["concept"][0]["variable"];

    return dataCountries;
  }

  List<Country> generateCountryList(var indicators) {
    List<Country> countries = [];

    for (var country in indicators) {
      countries.add(createCountry(country["id"], _codeToArea[country["id"]][1],
          _codeToArea[country["id"]][0], country["metatype"][0]["value"]));
    }

    return countries;
  }

  Country createCountry(
      String code, String imgCode, String name, String incomeGroup) {
    Country country = Country(code, imgCode, name, incomeGroup);
    return country;
  }
}
